### ISSUE TITLE
 Warning: componentWillReceiveProps has been renamed

### ISSUE THREAD

**Issue by kyliem29** [seleckis/react-stickyfill#11]
Getting the following warning when using this
`Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.`

Version: 0.2.5

**Comment by seleckis** [comment]
Hi, thank you for reporting. Yes, this lib should be rewritten to fit latest react patterns. Unfortunately I don't have time to do it now.

**Comment by seleckis** [comment]
Closing this due to this repository is not maintained any more. Just use `position: sticky`, it is supported by major browsers
