### ISSUE TITLE
Unable to install package behind a proxy

### ISSUE THREAD

**Issue by dcortes92** [seleckis/react-stickyfill#2]
I'm not able to install the package behind a corporate proxy. Here is the output when running `npm i -S react-stickyfill`:

![image](https://user-images.githubusercontent.com/3781536/34844319-a918ec22-f6d6-11e7-821a-a0d66ff3f243.png)

I was able to install 800+ dependencies behind the proxy but this one.

**Comment by dcortes92** [comment]
Closing this issue. I was able to install the package by running `git config --global http.proxy {proxyURL}`

**Comment by seleckis** [comment]
I'm happy that you have solved your issue.
