### ISSUE TITLE
Possible for child component to receive a prop to say that the sticky component is fixed?

### ISSUE THREAD

**Issue by joetidee** [seleckis/react-stickyfill#5]
Is it possible for the child component to receive an `isFixed` prop, so that the styles of the child can change based on whether the sticky component has stuck, e.g. a drop-shadow?

**Comment by seleckis** [comment]
Thank you for your question, I will do investigation of this feature tomorrow.

**Comment by seleckis** [comment]
Well, this component is just wrapper for polyfill which implements position: sticky for browsers which does not support this kind of position in CSS. But as far as I know CSS does not have sticky state now. Of course it is possible to imitate state in JS, but this is not the purpose is this component for.
